run:
  issues-exit-code: 0

linters:
  disable-all: true
  enable:
    - staticcheck
    - gosimple
    - ineffassign
    - errcheck
    - misspell
    - unparam
    - gofmt
    - goimports
    - deadcode
    - nestif
    - govet
    - golint
    - prealloc
    - depguard
    - dogsled
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - nakedret
    - rowserrcheck
    - scopelint
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - varcheck

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  goimports:
    local-prefixes: github.com/nakabonne/golintui
  golint:
    min-confidence: 0.3
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  maligned:
    suggest-new: true
  misspell:
    locale: US

