on:
  push:
    branches:
    - master
    paths-ignore:
    - 'README.md'
    - '.github/'
    - 'testdata/'
  pull_request:
    branches:
    - master
    paths-ignore:
    - 'README.md'
    - '.github/'
    - 'testdata/'
name: main
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build
    - name: Test
      run: go test -v -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt ./...
